name: Autonomous generation

on: 
  workflow_dispatch:
 # schedule:
 #   - cron: '0 */2 * * *'  # Repeat every 2h


jobs:
  prompt:
    runs-on: ubuntu-latest
    outputs:
      models: ${{ steps.set-matrix.outputs.models }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run prompt generator scripts
      working-directory: scripts
      id: set-matrix
      run: |
        export CONFIGPATH=config
        python modelsHelper.py $CONFIGPATH

        sh prompt.sh

    - name: Upload prompt
      uses: actions/upload-artifact@v4
      with:
        name: prompt
        path: scripts/prompt.txt


  ai:
    strategy:
      matrix:
        model: ${{fromJson(needs.prompt.outputs.models)}}
    runs-on: ubuntu-latest
    needs: prompt

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        
    - name: Download prompt
      uses: actions/download-artifact@v4
      with:
        name: prompt
        path: scripts

    - name: Config & run generator
      working-directory: scripts
      run: |
        export CONFIGPATH=config
        export MATRIXMODEL=${{ matrix.model }}
        export JOBINDEX=${{ strategy.job-index }}
        export RUNID=${{ github.run_id }}
        export RUNNUM=${{ github.run_number }}
        export WIDTH="768"
        export HEIGHT="768"
        export UPSCALE="3"

        sh image.sh   

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.model }}
        path: scripts/out

  push:
    runs-on: ubuntu-latest
    needs: ai
    steps:

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Clone repository
      uses: actions/checkout@v4
      with: 
        persist-credentials: false
        fetch-depth: 0
        ref: 'main'

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: scripts/tmp
        merge-multiple: true
        
    - name: Cleanup repository
      working-directory: scripts
      run: |
        export CONFIGPATH=config
        export RUNID=${{ github.run_id }}
        export RUNNUM=${{ github.run_number }}

        sh push.sh  

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
