name: Generator from request

on: 
  workflow_dispatch:
    inputs:
      custom_settings:
        description: Url for custom settings json file


jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.settings.outputs.config }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Check flow settings file
      working-directory: scripts
      id: settings
      env:
        SETTINGS: ${{ github.event.inputs.custom_settings }}
        CONFIG_FOLDER: '../config'
        
      run: python settings.py
      
    - name: Upload settings
      uses: actions/upload-artifact@v4
      with:
        name: settings
        path: config/tmp/settings.json

  txt2txt:
    runs-on: ubuntu-latest
    needs: config

    steps:
      - name: Clone repository
        if: ${{ fromJson(needs.config.outputs.config).txt2txt.active == 'true' }}
        uses: actions/checkout@v4


  txt2img:
    runs-on: ubuntu-latest
    needs: [config, txt2txt]
      
    strategy:
      matrix:
        ai: ${{ fromJson(needs.config.outputs.config).txt2img.matrix.ai-models }}
        num: ${{ fromJson(needs.config.outputs.config).txt2img.matrix.nums }}
    
    steps:
      - name: Clone repository
        if: ${{ fromJson(needs.config.outputs.config).txt2img.active == 'true' }}
        uses: actions/checkout@v4